# Generated by Django 6.0 on 2025-12-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('registered_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
